language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install -r test-requirements.txt
  - pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
# command to run tests
script:
  - python tests/pytests_data.py
  - python tests/pytests_trainer.py
  - python tests/pytests_transforms.py
  - python tests/pytests_multihead.py
